---
title: "visualizacoes_artigo"
author: "mimi"
date: "2026-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
library(ggplot2)
library(here)
library(showtext)
library(writexl)
library(patchwork)

font_add("Arial", paste0(here(),"/artigo/arial.ttf")) 
showtext_auto()
```


```{r}

load(paste0(here(),"/codigos/resultados_todos_20250706.RData"))

```


tabela_po_idade  > RMSE_TEFM
tabelas_por_idade_erro > RB_TEFM


tabela_larga_erro > RB_TFTM
tabela_larga > RMSE_TFTM
tabela_larga_PB > PB_TFT


```{r}



dados_plot <- tabelas_por_idade %>%
  bind_rows(.id = "faixa_idade") %>%
  pivot_longer(
    cols = -c(faixa_idade, mecanismo, proporcao),
    names_to = "Imputation method",
    values_to = "valor"
  ) %>%
  mutate(
    `RMSE MTFR` = as.numeric(str_replace(valor, ",", ".")),
    cenario = paste(mecanismo, proporcao)
  ) %>%
  select(-valor) %>% 
   mutate(
    `Imputation method` = case_when(
      `Imputation method` == "Mediana" ~ "Median",
      `Imputation method` == "Média" ~ "Mean",
      `Imputation method` == "Mediana condicional\na idade da mãe" ~ "MCMA", # Median conditional on maternal age
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao estado civil" ~ "MCMAMS", # Median conditional on maternal age and marital status
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao turno de nascimento" ~ "MCMABS",#Median conditional on maternal age and birth shift;
      `Imputation method` == "Mediana condicional \na idade da mãe\ne a função do responsável\npelo preenchimento da DN" ~ "MCMARR", # Median conditional on maternal age and the role of the person responsible for completing the Live Birth Declaration
      `Imputation method` == "Análise de casos completos"~ "CCA", #COMPLETE CASE ANALISES
      TRUE ~ `Imputation method`
    )
  ) %>% 
  rename( "Age group" = faixa_idade,
          Percentage = proporcao,
          Mecanism = mecanismo, 
          Setting = cenario
          ) %>% 
  mutate(
    Mecanism = case_when(
      Mecanism == "MA" ~ "MAR",
      Mecanism == "MCA" ~ "MCAR",
      Mecanism == "MNA" ~ "MNAR"
  ),
   Setting = Setting %>%
      str_replace("^MA", "MAR") %>%
      str_replace("^MCA", "MCAR") %>%
      str_replace("^MNA", "MNAR"))

REQM_TEFM = ggplot(dados_plot,
       aes(x =`Age group`,
           y =  `Imputation method`,
           fill = `RMSE MTFR`)) +
  geom_tile(color = "white") +
  labs( title = "", #"RMSE MTFR",
       y= "Imputation method",
       x= "Age group")+
  facet_wrap(~ Setting) +
  scale_fill_gradient2(
    low = "#B2182B",    # negativos
    mid = "white",      # próximo de 0
    high = "#2166AC",   # positivos
    midpoint = 0,
    name = "RMSE"
  ) +
  theme_minimal(base_family = "Arial")+
  theme(
    axis.text.x = element_text(angle = 90, hjust = 0.5),
    plot.title = element_text(hjust = 0.5)
  )

# ggsave("RMSE_MTFR.png",REQM_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
# ggsave("RMSE_MTFR.pdf",REQM_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
# write_xlsx(dados_plot, paste0(here(), "/artigo", "/RMSE_MTFR.xlsx"))
```




```{r}

dados_plot_erro <- tabelas_por_idade_erro %>%
  bind_rows(.id = "faixa_idade") %>%
  pivot_longer(
    cols = -c(faixa_idade, mecanismo, proporcao),
    names_to = "Imputation method",
    values_to = "valor"
  ) %>%
  mutate(
    `RB MTFR` = as.numeric(str_replace(valor, ",", ".")),
    cenario = paste(mecanismo, proporcao)
  ) %>%
  select(-valor) %>% 
   mutate(
    `Imputation method` = case_when(
      `Imputation method` == "Mediana" ~ "Median",
      `Imputation method` == "Média" ~ "Mean",
      `Imputation method` == "Mediana condicional\na idade da mãe" ~ "MCMA", # Median conditional on maternal age
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao estado civil" ~ "MCMAMS", # Median conditional on maternal age and marital status
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao turno de nascimento" ~ "MCMABS",#Median conditional on maternal age and birth shift;
      `Imputation method` == "Mediana condicional \na idade da mãe\ne a função do responsável\npelo preenchimento da DN" ~ "MCMARR", # Median conditional on maternal age and the role of the person responsible for completing the Live Birth Declaration
      `Imputation method` == "Análise de casos completos"~ "CCA", #COMPLETE CASE ANALISES
      TRUE ~ `Imputation method`
    )
  ) %>% 
  rename( "Age group" = faixa_idade,
          Percentage = proporcao,
          Mecanism = mecanismo, 
          Setting = cenario
          ) %>% 
  mutate(
    Mecanism = case_when(
      Mecanism == "MA" ~ "MAR",
      Mecanism == "MCA" ~ "MCAR",
      Mecanism == "MNA" ~ "MNAR"
  ),
   Setting = Setting %>%
      str_replace("^MA", "MAR") %>%
      str_replace("^MCA", "MCAR") %>%
      str_replace("^MNA", "MNAR"))


rb_TEFM = ggplot(dados_plot_erro,
       aes(x =`Age group`,
           y =  `Imputation method`,
           fill = `RB MTFR`)) +
  geom_tile(color = "white") +
  labs(title = "",# Raw bias MTFR
       y= "Imputation method",
       x= "Age group")+
  facet_wrap(~ Setting) +
   scale_fill_gradient2(
    low = "#B2182B",    
    mid = "white",      
    high = "#2166AC",   
    midpoint = 0,
    name = "Absolute\nerror"
  ) +
  theme_minimal(base_family = "Arial") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 0.5),
    plot.title = element_text(hjust = 0.5)
  )


ggsave("AE_MTFR.png",rb_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
ggsave("AE_MTFR.pdf",rb_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
write_xlsx(dados_plot_erro %>% rename( `Absolute error MTFR`=`RB MTFR`), paste0(here(), "/artigo", "/AE_MTFR.xlsx"))
```



```{r}

dados_plot_PB <- tabelas_por_idade_PB %>%
  bind_rows(.id = "faixa_idade") %>%
  pivot_longer(
    cols = -c(faixa_idade, mecanismo, proporcao),
    names_to = "Imputation method",
    values_to = "valor"
  ) %>%
  mutate(
    `Percent bias MTFR` = as.numeric(str_replace(valor, ",", ".")),
    cenario = paste(mecanismo, proporcao)
  ) %>%
   select(-valor) %>% 
   mutate(
    `Imputation method` = case_when(
      `Imputation method` == "Mediana" ~ "Median",
      `Imputation method` == "Média" ~ "Mean",
      `Imputation method` == "Mediana condicional\na idade da mãe" ~ "MCMA", # Median conditional on maternal age
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao estado civil" ~ "MCMAMS", # Median conditional on maternal age and marital status
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao turno de nascimento" ~ "MCMABS",#Median conditional on maternal age and birth shift;
      `Imputation method` == "Mediana condicional \na idade da mãe\ne a função do responsável\npelo preenchimento da DN" ~ "MCMARR", # Median conditional on maternal age and the role of the person responsible for completing the Live Birth Declaration
      `Imputation method` == "Análise de casos completos"~ "CCA", #COMPLETE CASE ANALISES
      TRUE ~ `Imputation method`
    )
  ) %>% 
  rename( "Age group" = faixa_idade,
          Percentage = proporcao,
          Mecanism = mecanismo, 
          Setting = cenario
          ) %>% 
  mutate(
    Mecanism = case_when(
      Mecanism == "MA" ~ "MAR",
      Mecanism == "MCA" ~ "MCAR",
      Mecanism == "MNA" ~ "MNAR"
  ),
   Setting = Setting %>%
      str_replace("^MA", "MAR") %>%
      str_replace("^MCA", "MCAR") %>%
      str_replace("^MNA", "MNAR"))


PB_TEFM = ggplot(dados_plot_PB,
      aes(x =`Age group`,
           y =  `Imputation method`,
           fill = `Percent bias MTFR`)) +
  geom_tile(color = "white") +
  labs(title = "",#"Percent bias MTFR",
       y= "Imputation method",
       x= "Age group")+
  facet_wrap(~ Setting) +
   scale_fill_gradient2(
    low = "#B2182B",    
    mid = "white",      
    high = "#2166AC",   
    midpoint = 0,
    name = "Relative\nerror"
  ) +
  theme_minimal(base_family = "Arial") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 0.5),
    plot.title = element_text(hjust = 0.5)
  )



ggsave("RE_TEFM.png",PB_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
ggsave("RE_TEFM.pdf",PB_TEFM, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
write_xlsx(dados_plot_PB %>% rename(`Relative error` = `Percent bias MTFR`), paste0(here(), "/artigo", "/RE_TEFM.xlsx"))

```








```{r}


padroniza_metodo <- function(df){

  df %>%
pivot_longer(
      cols = -c(mecanismo, proporcao),
      names_to = "Imputation method",,
      values_to = "valor"
    ) %>%
mutate(
      valor = as.numeric(str_replace(valor, ",", ".")),
      `Imputation method` = case_when(
      `Imputation method` == "Mediana" ~ "Median",
      `Imputation method` == "Média" ~ "Mean",
      `Imputation method` == "Mediana condicional\na idade da mãe" ~ "MCMA", # Median conditional on maternal age
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao estado civil" ~ "MCMAMS", # Median conditional on maternal age and marital status
      `Imputation method` == "Mediana condicional\n a idade da mãe\ne ao turno de nascimento" ~ "MCMABS",#Median conditional on maternal age and birth shift;
      `Imputation method` == "Mediana condicional \na idade da mãe\ne a função do responsável\npelo preenchimento da DN" ~ "MCMARR", # Median conditional on maternal age and the role of the person responsible for completing the Live Birth Declaration
      `Imputation method` == "Análise de casos completos"~ "CCA", #COMPLETE CASE ANALISES
      TRUE ~ `Imputation method`
        )
    ) |> 
    filter( `Imputation method` != "CCA") %>% 
  rename(Percentage = proporcao,
          Mecanism = mecanismo
          ) %>% 
  mutate(
    Mecanism = case_when(
      Mecanism == "MA" ~ "MAR",
      Mecanism == "MCA" ~ "MCAR",
      Mecanism == "MNA" ~ "MNAR"
  ))

  
}

#-----------------------------
# REQM
#-----------------------------

dados_REQM <- padroniza_metodo(tabela_larga) %>%
  mutate(indicador = "RMSE")

#-----------------------------
# Erro bruto
#-----------------------------

dados_RB <- padroniza_metodo(tabela_larga_erro) %>%
  mutate(indicador = "Absolute error")

#-----------------------------
# Viés relativo
#-----------------------------

dados_PB <- padroniza_metodo(tabela_larga_PB) %>%
  mutate(indicador = "Relative error")

#-----------------------------
# Junta tudo
#-----------------------------

dados_final <- bind_rows(
  dados_REQM,
  dados_RB,
  dados_PB
)



faz_grafico <- function(dados, legenda, titulo_x,titulo_y){ #titulo, 

  ggplot(
    dados,
    aes(
      x = Percentage,
      y = `Imputation method`,
      fill = valor
    )
  ) +

    geom_tile(color = "white") +

    facet_wrap(~ Mecanism) +

    scale_fill_gradient2(
      low = "#B2182B",
      mid = "white",
      high = "#2166AC",
      midpoint = 0,
      name = legenda
    ) +

    labs(
      # title = titulo,
      x = titulo_x,
      y = titulo_y
    ) +

    theme_minimal(base_family = "Arial") +

    theme(
      axis.text.x = element_text(
        angle = 90,
        hjust = 0.5
      ),

      plot.title = element_blank()
    )
}


g_REQM <- faz_grafico(
  dados_REQM,
   # titulo= "",
  legenda ="RMSE           ",
  titulo_x= "",
  titulo_y =""
)

g_RB <- faz_grafico(
  dados_RB,
   # titulo="",
  "Absolute error",
  titulo_x= "",
  titulo_y = "Imputation method"
)

g_PB <- faz_grafico(
  dados_PB,
   # titulo ="",
  "Relative error",
  titulo_x = "Percentage of missing data",
  titulo_y =""
)



g_final <- (
  g_REQM /
  g_RB /
  g_PB
)


ggsave("TFR.png",g_final, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)
ggsave("TFR.pdf",g_final, width = 16.5, height = 12, units = "cm", path = paste0(here(), "/artigo"),  dpi=300)

tabela_TFR = bind_rows( dados_REQM,
dados_RB,
dados_PB)

write_xlsx(tabela_TFR, paste0(here(), "/artigo", "/tabel_TFR.xlsx"))

# ggsave("Indicadores_TFTM.png",g_final,path = here(),width = 15,height = 15,units = "cm",dpi = 300)
```








